// ESLint v9+ flat config format
export default [
    {
        files: ["frontend/public/js/**/*.js"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "script",
            globals: {
                // Browser globals
                window: "readonly",
                document: "readonly",
                console: "readonly",
                fetch: "readonly",
                localStorage: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                URLSearchParams: "readonly",
                // vis.js globals
                vis: "readonly",
                // App-specific globals from other files
                API_BASE: "readonly",
                searchWords: "readonly",
                getWord: "readonly",
                getEtymologyTree: "readonly",
                getEtymologyChain: "readonly",
                network: "readonly",
                searchedWordId: "readonly",
                nodeColorOverrides: "readonly",
                updateGraph: "readonly",
                centerNode: "readonly",
                centerViewport: "readonly",
                LANGUAGE_FAMILY_COLORS: "readonly",
                buildLegendHTML: "readonly",
                LAYOUTS: "readonly",
                currentLayout: "writable",
                selectWord: "readonly",
                router: "readonly",
            },
        },
        rules: {
            "semi": ["error", "always"],
            "quotes": ["error", "double"],
            "indent": ["error", 4],
            "no-unused-vars": "warn",
            "no-undef": "error",
            "no-console": "off",
            "max-len": ["warn", {
                "code": 120,
                "ignoreUrls": true,
                "ignoreStrings": true,
                "ignoreTemplateLiterals": true,
            }],
        },
    },
    {
        files: ["frontend/tests/**/*.js"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: {
                window: "readonly",
                document: "readonly",
                console: "readonly",
                URLSearchParams: "readonly",
                __dirname: "readonly",
                // Vitest globals
                describe: "readonly",
                it: "readonly",
                expect: "readonly",
                vi: "readonly",
                beforeEach: "readonly",
                afterEach: "readonly",
            },
        },
        rules: {
            "semi": ["error", "always"],
            "quotes": ["error", "double"],
            "indent": ["error", 4],
            "no-unused-vars": "warn",
            "no-undef": "error",
            "no-console": "off",
            "max-len": ["warn", {
                "code": 120,
                "ignoreUrls": true,
                "ignoreStrings": true,
                "ignoreTemplateLiterals": true,
            }],
        },
    },
    {
        files: ["tests/e2e/**/*.js"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
        },
        rules: {
            "semi": ["error", "always"],
            "quotes": ["error", "double"],
            "indent": ["error", 4],
            "no-unused-vars": "warn",
            "no-undef": "off",
            "no-console": "off",
            "max-len": ["warn", {
                "code": 120,
                "ignoreUrls": true,
                "ignoreStrings": true,
                "ignoreTemplateLiterals": true,
            }],
        },
    },
];
