"""Golden-fixture tests for the seed layout module.

These fixtures were generated by exercising the original JS implementation
(computeTreePositions and friends) in frontend/public/js/graph.js, so a match
here is proof of line-for-line parity between the Python port and the JS
source it replaces — including exact BFS ordering, not just final result
shape.
"""

import json
from pathlib import Path

import pytest
from app.services.layout.seed import compute_tree_positions

FIXTURES_DIR = Path(__file__).resolve().parents[2] / "tests" / "fixtures" / "layout"


def _load_fixture(name: str):
    with open(FIXTURES_DIR / name) as f:
        return json.load(f)


def _assert_positions_match(actual: dict, expected: dict) -> None:
    assert set(actual.keys()) == set(expected.keys())
    for node_id, expected_pos in expected.items():
        actual_pos = actual[node_id]
        assert actual_pos["x"] == pytest.approx(expected_pos["x"], rel=1e-9, abs=1e-12), (
            f"x mismatch for {node_id}"
        )
        assert actual_pos["y"] == pytest.approx(expected_pos["y"], rel=1e-9, abs=1e-12), (
            f"y mismatch for {node_id}"
        )


@pytest.mark.tier0
def test_radial_tree_matches_golden_fixture():
    """compute_tree_positions matches graph.js's computeTreePositions for a
    branching etymology graph with levels (radial path), including a
    disconnected orphan node placed by the fan-out branch."""
    nodes = [
        {"id": "root:PIE", "level": -2},
        {"id": "mid:ProtoGermanic", "level": -1},
        {"id": "word:English", "level": 0},
        {"id": "child1:English", "level": 1},
        {"id": "child2:English", "level": 1},
        {"id": "grandchild:English", "level": 2},
        {"id": "orphan:French", "level": 0},
    ]
    edges = [
        {"from": "mid:ProtoGermanic", "to": "root:PIE", "label": "inh"},
        {"from": "word:English", "to": "mid:ProtoGermanic", "label": "inh"},
        {"from": "child1:English", "to": "word:English", "label": "der"},
        {"from": "child2:English", "to": "word:English", "label": "der"},
        {"from": "grandchild:English", "to": "child1:English", "label": "der"},
        {"from": "child2:English", "to": "grandchild:English", "label": "cog"},
    ]

    expected = _load_fixture("radial-tree.json")
    actual = compute_tree_positions(nodes, edges, "root:PIE")

    _assert_positions_match(actual, expected)


@pytest.mark.tier0
def test_single_node_no_edges_matches_golden_fixture():
    """The `!edges.length` early-return branch: a lone node with no edges at
    all just gets placed at the origin."""
    nodes = [{"id": "solo:English", "level": 0}]

    expected = _load_fixture("single-node.json")
    actual = compute_tree_positions(nodes, [], "solo:English")

    _assert_positions_match(actual, expected)


@pytest.mark.tier0
def test_deep_chain_matches_golden_fixture():
    """A 6-node unbranched chain exercises the radial path's single-child
    angular-span propagation and its float tails (e.g. sin(pi) != 0)."""
    nodes = [{"id": f"n{i}:English", "level": i - 2} for i in range(6)]
    edges = [{"from": nodes[i + 1]["id"], "to": nodes[i]["id"], "label": "inh"} for i in range(5)]

    expected = _load_fixture("deep-chain.json")
    actual = compute_tree_positions(nodes, edges, "n0:English")

    _assert_positions_match(actual, expected)


@pytest.mark.tier0
def test_linear_tree_matches_golden_fixture():
    """The NO-LEVELS (concept-map) path: nodes have no "level" key at all
    (not even None), which must be treated the same as an explicit level of
    None for the hasLevels detection. Includes a disconnected iso node."""
    nodes = [
        {"id": "center:English"},
        {"id": "leaf1:French"},
        {"id": "leaf2:German"},
        {"id": "leaf3:Spanish"},
        {"id": "deep:Italian"},
        {"id": "iso:Latin"},
    ]
    edges = [
        {"from": "center:English", "to": "leaf1:French"},
        {"from": "center:English", "to": "leaf2:German"},
        {"from": "center:English", "to": "leaf3:Spanish"},
        {"from": "leaf1:French", "to": "deep:Italian"},
    ]

    expected = _load_fixture("linear-tree.json")
    actual = compute_tree_positions(nodes, edges, "center:English")

    _assert_positions_match(actual, expected)


@pytest.mark.tier0
def test_empty_nodes_returns_empty_dict():
    """`!nodes.length` branch: no nodes at all short-circuits to {}."""
    assert compute_tree_positions([], [], None) == {}
    assert compute_tree_positions([], [], "root") == {}


@pytest.mark.tier0
def test_missing_root_id_returns_empty_dict():
    """`!rootId` branch: nodes exist but no root_id is given."""
    nodes = [{"id": "solo:English", "level": 0}]
    assert compute_tree_positions(nodes, [], None) == {}
