"""Golden-fixture tests for the edge_params layout module.

These fixtures were generated by exercising the original JS implementations
in frontend/public/js/graph.js and concept-map.js, so a match here is proof
of line-for-line parity between the Python port and the JS source it replaces.
"""

import json
from pathlib import Path

import pytest
from app.services.layout.edge_params import (
    build_concept_edges,
    build_vis_edges,
    similarity_to_edge_length,
)

FIXTURES_DIR = Path(__file__).resolve().parents[2] / "tests" / "fixtures" / "layout"


def _load_fixture(name: str):
    with open(FIXTURES_DIR / name) as f:
        return json.load(f)


@pytest.mark.tier0
def test_build_vis_edges_matches_golden_fixture():
    """build_vis_edges output matches graph.js's buildVisEdges byte-for-byte
    (modulo float representation) for a representative etymology graph."""
    edges = [
        {"from": "root:PIE", "to": "mid:ProtoGermanic", "label": "inh"},
        {"from": "mid:ProtoGermanic", "to": "word:English", "label": "inh"},
        {"from": "child1:English", "to": "word:English", "label": "der"},
        {"from": "child2:English", "to": "word:English", "label": "der"},
        {"from": "cognate:German", "to": "word:English", "label": "cog"},
        {"from": "mention:Latin", "to": "word:English", "label": "mention"},
    ]

    expected = _load_fixture("edge-params.json")
    actual = build_vis_edges(edges)

    assert len(actual) == len(expected)
    for actual_edge, expected_edge in zip(actual, expected, strict=True):
        assert actual_edge["from"] == expected_edge["from"]
        assert actual_edge["to"] == expected_edge["to"]
        assert actual_edge["label"] == expected_edge["label"]
        assert actual_edge["rawType"] == expected_edge["rawType"]
        assert actual_edge["arrows"] == expected_edge["arrows"]
        assert actual_edge["dashes"] == expected_edge["dashes"]
        assert actual_edge["color"]["color"] == expected_edge["color"]["color"]
        assert actual_edge["color"]["highlight"] == expected_edge["color"]["highlight"]
        assert actual_edge["length"] == pytest.approx(expected_edge["length"])
        assert actual_edge["springConstant"] == pytest.approx(expected_edge["springConstant"])


@pytest.mark.tier0
def test_similarity_to_edge_length_matches_golden_fixture():
    """similarity_to_edge_length matches concept-map.js's
    similarityToEdgeLength for a spread of representative similarity scores."""
    expected = _load_fixture("similarity-to-edge-length.json")

    for similarity_str, expected_length in expected.items():
        similarity = float(similarity_str)
        assert similarity_to_edge_length(similarity) == pytest.approx(expected_length)


@pytest.mark.tier0
def test_build_concept_edges_matches_golden_fixture():
    """build_concept_edges output matches concept-map.js's buildConceptEdges
    (with the show-etymology-edges checkbox replaced by an explicit bool)."""
    phonetic_edges = [
        {
            "source": "fire:English",
            "target": "feuer:German",
            "similarity": 0.82,
            "turchin_match": False,
        },
        {
            "source": "fire:English",
            "target": "ignis:Latin",
            "similarity": 0.35,
            "turchin_match": True,
        },
    ]
    etym_edges = [
        {
            "source": "fire:English",
            "target": "feuer:German",
            "relationship": "cognate",
        },
    ]

    expected = _load_fixture("concept-edges.json")
    actual = build_concept_edges(phonetic_edges, etym_edges, True)

    assert len(actual) == len(expected)
    for actual_edge, expected_edge in zip(actual, expected, strict=True):
        assert actual_edge["from"] == expected_edge["from"]
        assert actual_edge["to"] == expected_edge["to"]
        assert actual_edge["dashes"] == expected_edge["dashes"]
        assert actual_edge["color"]["color"] == expected_edge["color"]["color"]
        assert actual_edge["color"]["highlight"] == expected_edge["color"]["highlight"]
        assert actual_edge["width"] == pytest.approx(expected_edge["width"])
        assert actual_edge["length"] == pytest.approx(expected_edge["length"])
        assert actual_edge["springConstant"] == pytest.approx(expected_edge["springConstant"])
        assert actual_edge["title"] == expected_edge["title"]
        assert actual_edge["edgeType"] == expected_edge["edgeType"]
        assert actual_edge.get("arrows") == expected_edge.get("arrows")


@pytest.mark.tier0
def test_build_concept_edges_excludes_etymology_when_flag_false():
    """When include_etymology_edges is False, only phonetic edges are returned
    and etym edges do not contribute to degree-based length/spring computation."""
    phonetic_edges = [
        {
            "source": "fire:English",
            "target": "feuer:German",
            "similarity": 0.82,
            "turchin_match": False,
        },
    ]
    etym_edges = [
        {
            "source": "fire:English",
            "target": "feuer:German",
            "relationship": "cognate",
        },
        {
            "source": "fire:English",
            "target": "ignis:Latin",
            "relationship": "related",
        },
    ]

    actual = build_concept_edges(phonetic_edges, etym_edges, False)

    assert len(actual) == 1
    assert actual[0]["edgeType"] == "phonetic"
    # degree(fire)=1, degree(feuer)=1 -> combined=2, max_deg=1 (etym edges excluded)
    assert actual[0]["springConstant"] == pytest.approx(0.008 / 1)
